---
- name: Set up worstation based on Ubuntu Server with Sway etc.
  hosts: localhost
  become: yes
  vars:
    for_user: joseph
  tasks:
    - name: Add PPA for alacritty
      apt_repository:
        repo: 'ppa:aslatter/ppa'
        state: present
    - name: Add PPA for pipewire
      apt_repository:
        repo: 'ppa:pipewire-debian/pipewire-upstream'
        state: present
    - name: Update apt cache and install packages
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - zsh
        - zsh-syntax-highlighting
        - curl
        - wget
        - unzip
        - silversearcher-ag
        - pass
        - openvpn
        - tmux
        - build-essential
        - sway
        - upower
        - udisks2
        - fzf
        - alacritty
        - libwayland-egl1
        - pipewire
        - pipewire-audio-client-libraries
    - name: Install snaps
      command: snap install --classic {{item}}
      with_items:
        - firefox
        - chromium
        - goland
    - name: Ensure user directories exist
      file: path={{item}} state=directory owner={{for_user}} group={{for_user}} mode=774 recurse=yes
      with_items:
        - /home/{{for_user}}/.cache/zsh
        - /home/{{for_user}}/.config/systemd/user
        - /home/{{for_user}}/.config/sway
        - /home/{{for_user}}/.config/alacritty
        - /home/{{for_user}}/go/bin
        - /home/{{for_user}}/go/pkg
        - /home/{{for_user}}/go/src
        - /home/{{for_user}}/bin
        - /home/{{for_user}}/projects
    - name: Copy user files
      copy: src={{item.src}} dest={{item.dest}} owner={{for_user}} group={{for_user}} mode=664 force=no
      with_items:
        - { src: "files/dotprofile", dest: "/home/{{for_user}}/.profile" }
        - { src: "files/dotzshrc", dest: "/home/{{for_user}}/.zshrc" }
        - { src: "files/dottmux.conf", dest: "/home/{{for_user}}/.tmux.conf" }
        - { src: "files/ssh-agent.service", dest: "/home/{{for_user}}/.config/systemd/user/ssh-agent.service" }
        - { src: "files/swayconfig", dest: "/home/{{for_user}}/.config/sway/config" }
        - { src: "files/alacritty.toml", dest: "/home/{{for_user}}/.config/alacritty/alacritty.toml" }
    - name: Use zsh
      command: usermod --shell /usr/bin/zsh {{for_user}}
    - name: Enable user services
      become_user: "{{for_user}}"
      ansible.builtin.systemd_service:
        daemon_reload: true
        name: "{{ item }}.service"
        state: started
        enabled: true
        scope: user
      loop:
        - ssh-agent
        - pipewire
        - pipewire-pulse
    - name: Install zsh autosuggestions
      become_user: "{{for_user}}"
      git: repo=https://github.com/zsh-users/zsh-autosuggestions.git dest=/home/{{for_user}}/projects/zsh-autosuggestions update=no
         
